### ISSUE TITLE
cannot solve mxn matrix

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-java-client#45]
when I specify my matrix like this:

```
GHMRequest ghmRequest = new GHMRequest();
ghmRequest.addOutArray("distances");
ghmRequest.addOutArray("times");
ghmRequest.setVehicle("car");
ghmRequest.addFromPoints(Arrays.asList(new GHPoint(52.557151,13.515244)))
                .addToPoints(Arrays.asList(new GHPoint(52.557151,13.515244),new GHPoint(52.454545,13.295517)));
```

and try to calculate a matrix with the matrix client (no matter whether sync or batch client), I get this:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.graphhopper.api.GHMatrixAbstractRequester.fillResponseFromJson(GHMatrixAbstractRequester.java:153)
	at com.graphhopper.api.GHMatrixSyncRequester.route(GHMatrixSyncRequester.java:95)
	at com.graphhopper.api.GraphHopperMatrixWeb.route(GraphHopperMatrixWeb.java:44)
```

**Comment by karussell** [comment]
I can reproduce this and will fix.

**Comment by karussell** [comment]
Can you build the latest master and try with this version 0.9-SNAPSHOT if it is fixed?

**Comment by oblonski** [comment]
Perfect. Works now! Thanks. 👍

**Comment by karussell** [comment]
Will be deployed as 0.8.2-3 in the next hour
